version: "3.6"
services:
  phoxicontrol:
    build:
      context: ./context
      dockerfile: $PWD/Dockerfile
      # args:
      #   buildno: 1
    image: phoxi_ros:latest
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /dev/shm:/dev/shm
      - $PWD/context/phoxi_camera:/root/catkin_ws/src/phoxi_camera
    privileged: true
    environment:
      - DISPLAY
      - DOCKER=1
      - QT_X11_NO_MITSHM=1
      - SHELL
    stop_signal: SIGKILL
    security_opt:
      - apparmor=unconfined
    logging:
      driver: journald
      options:
        tag: '{{.ImageID}}/{{.Name}}/{{.ID}}'
    command: /bin/bash -c "cd ~/catkin_ws && source ~/catkin_ws/devel/setup.bash && catkin_make && source ~/catkin_ws/devel/setup.bash && PhoXiControl | roslaunch phoxi_camera phoxi_camera.launch"
